on: 
  push:
    paths-ignore:
    - 'docs/**'
    - README.md
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install latest buildx
        run: mkdir -p ~/.docker/cli-plugins && wget -O ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64 && chmod a+x  ~/.docker/cli-plugins/docker-buildx
      - name: build
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_EXPERIMENTAL: enabled
        working-directory: ./integration/docker
        run: docker buildx bake -f ./docker-compose.base.yaml -f ./docker-compose.worker.yaml -f ./docker-compose.producer.yaml --load  
      - name: test-multi
        working-directory: ./integration/tests
        run: ./multi.sh
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.ORG_CR_WRITER_USER }}
          password: ${{ secrets.ORG_CR_WRITER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Push to GHCR
        uses: docker/build-push-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          push: true
          tags: ghcr.io/soluto/dqd:${{ steps.get_version.outputs.version }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
      - name: Push to Dockerhub
        uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: solutodqd
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: soluto/dqd
          tag_with_sha: ${{ github.ref == 'refs/heads/master'}}
          tag_with_ref: ${{ github.ref != 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}